---
- name: Elk playbook
  hosts: Elk
  remote_user: azadmin
  become: true
  tasks:

  - name: The docker engine used for running containers.
    apt:
      update_cache: yes
      force_apt_get: yes
      name: docker.io
      state: present

  - name: Package used to install python software.
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Python client for docker. required by anisible to control the state of docker containers.
    pip:
      name: docker
      state: present

  - name: Memory
    sysctl:
      name: vm.max_map_count
      value: '262144'
      state: present
      reload: yes

  - name: Downloads and launches a docker elk container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
        -  5601:5601
        -  9200:9200
        -  5044:5044


